### ISSUE TITLE
error in parsing import assertions.

### ISSUE THREAD

**Issue by fusionstrings** [jspm/generator#127]
Parsing import assertion throws.

Following is a reproduction of the issue. The example uses chomp but since the issue originates from babel parser, probably it's caused by generator.

https://github.com/fusionstrings/jspm-generator-json-import-error

**Comment by guybedford** [comment]
The repo seems to be not found, it would be useful to see the reproduction to fix the issue.

**Comment by fusionstrings** [comment]
> The repo seems to be not found, it would be useful to see the reproduction to fix the issue.

I accidentally made the repo private. Made it public now.

The code similar to below is throwing due to parsing error.

```js
import {
  contentType,
  lookup,
} from "https://deno.land/x/media_types@v3.0.2/mod.ts";
import json from "./static-resources.json" assert { type: "json" };

Object.values(json).forEach((value) => {
  console.log(contentType(lookup(value)));
});
```
