### ISSUE TITLE
Support "uninstalling" packages

### ISSUE THREAD

**Issue by vovacodes** [jspm/generator#131]
One of the issues we've run into at Framer is being unable to remove a package from the import map. This causes unnecessary bloat. The API could look something like this: 

```ts
const generator = new Generator({
        mapUrl: "about:blank",
        inputMap,
})

await generator.uninstall("lodash")

return generator.getMap()
```

**Comment by guybedford** [comment]
`generator.uninstall` is now implemented in https://github.com/jspm/generator/issues/132.
