### ISSUE TITLE
Extract partial import map required by a specific module(s)

### ISSUE THREAD

**Issue by vovacodes** [jspm/generator#132]
Another use-case we have at Framer arises from the modules copy/paste functionality. In Framer every project has its own import map, so when we copy/paste a component from one project to another we need to bring the "source" project's import map along with it and merge it with the "destination" one.

The reasons we won't simply use `generator.traceInstall(pastedModuleURL)` are:
- We want to preserve the resolutions that this module was using in the source project (except the dependencies that are also present in the destination project, which take precedence in this case).
- We want the paste functionality to work as "instant" as possible, and simply merging two existing import maps is the fastest possible solution.

Unfortunately this solution results in bloating the destination import map with a bunch of unnecessary resolutions that are not even used by the pasted module. A better alternative would be to merge only the part of the source import map that we know is required by the pasted module.

The API can be:
```ts
const generator = new Generator({
        mapUrl: "about:blank",
        inputMap,
})

// Extracts the part of the `inputMap` required by module1 and module2.
const submap = await generator.extractSubmap([module1URL, module2URL])
```

**Comment by guybedford** [comment]
What if we had a `generator.installAll()` or `generator.reinstall()` operation which would reinstall all the top-level installs, and apply pruning? The `inputMap` would imply the top-level imports so that `module1URL` and `module2URL` shouldn't be necessary. This seems to have a nice compatibility with a `generator.uninstall()`.

**Comment by guybedford** [comment]
@vovacodes would it make sense to treat all `"imports"` keys as entry points?

**Comment by guybedford** [comment]
This is now implemented in https://github.com/jspm/generator/pull/134 as `generator.extractMap(['react', '...'])`.
