### ISSUE TITLE
Automatic env detection from input map

### ISSUE THREAD

**Issue by guybedford** [jspm/generator#145]
Now that we are doing comprehensive input map analysis and decomposition, we can also possibly detect the conditional environment from the input map based on what resolutions are present.

This could also `env` to be defaulted correctly when not otherwise provided.

Although not full-proof,  since having no env mappings would effectively lose this information, it may well provide a good enough approach to this long-standing problem.

**Comment by Bubblyworld** [comment]
Just some notes for my future brain, we chatted about this and came to the conclusion that having an explicit `"env"` field in the output maps has a lot of benefits, like making users aware that import maps are _environment specific_ by nature. On the other hand it will cause some warnings, so we should probably revisit this once jspm gets traction.

**Comment by guybedford** [comment]
Let's move this discussion into being tracked as lockfile support in https://github.com/jspm/generator/issues/262 for now. We can always reopen this approach if the decisions change though.
