### ISSUE TITLE
Top-level resolutions

### ISSUE THREAD

**Issue by guybedford** [jspm/generator#172]
We need to ensure `"resolutions"` apply for top-level installs, these still seem to be getting missed somehow.

**Comment by Bubblyworld** [comment]
@guybedford Do you know/remember how to reproduce this? Setting `"resolutions"` on the generator options seems to work fine for me for top-level installs, secondary installs, and linking. For instance, this works:

```js
let generator = new Generator({
  mapUrl: import.meta.url,
  env: ["production", "browser"],
  resolutions: {
    semver: "6.2.0",
  },
});

await generator.install("semver@latest");
let json = generator.getMap();
assert.ok(json.imports["semver"]);
assert.ok(json.imports["semver"].includes("6.2.0")); // passes fine
```

**Comment by guybedford** [comment]
Tests included, closing as resolved.
