### ISSUE TITLE
Incorrect import version added to import map

### ISSUE THREAD

**Issue by zachsa** [jspm/generator#175]
Using version `1.0.0-beta.36`:

package.json has this dependency: `"graphql": "^16.6"`. But running the generator I get an older version added as an import to the import map: `"graphql": "https://ga.jspm.io/npm:graphql@16.5.0/index.mjs",`

Would it be possible for the generator to throw an error if it isn't able to resolve versions as specified in package.lock or package-lock.json?

The code I'm using is this:

```
const generator = new Generator({
  mapUrl: pathToFileURL(TARGET),
  env: ['browser', NODE_ENV, 'module'],
  defaultProvider: 'jspm',
})

const htmlSource = await readFile('source.html', 'utf-8')
const pins = await generator.addMappings(htmlSource)
const html = await generator.htmlInject(htmlSource, {
  trace: true,
  pins,
  preload: false,
  integrity: false,
  esModuleShims: true,
})
```

**Comment by zachsa** [comment]
This is related to similar issues - https://github.com/jspm/generator/issues/166, https://github.com/jspm/generator/issues/158, https://github.com/jspm/generator/issues/157

**Comment by guybedford** [comment]
GraphQL 16.6.0 had not been built yet, I've triggered a build and it should be working now. You can check the latest version via `https://ga.jspm.io/npm:graphql`.

**Comment by guybedford** [comment]
Note that you can also trigger missing builds via the rebuild API.
