### ISSUE TITLE
Missing library - https://ga.jspm.io/npm:d3@7.7.0/package.json

### ISSUE THREAD

**Issue by zachsa** [jspm/generator#188]
Hi,

`d3.js@7.7.0` does not seem to be available yet, although I did request a build via the build API yesterday. Usually this is quite quick, so I suspect there may be a problem with this particular package

**Comment by guybedford** [comment]
This is correct - if you look at the package on npm you will see that it is a malicious package that is made to confuse users of the real `d3` - https://www.npmjs.com/package/d3.js.

We should have better exception handling around cases like this to report what is going on.

**Comment by zachsa** [comment]
Ah sorry. Here is the link https://www.npmjs.com/package/d3?activeTab=versions.

I didn't realize d3.js isn't the correct name. However it's the real package that is broken

**Comment by guybedford** [comment]
This seems correct to me?

https://jspm.org/sandbox#H4sIAAAAAAAAA42XTXPbNhCG7/4VG+aStCYZWXGTKpJHzkfTdKxMJx5P0yMErEU0IMEAoG250//eJSgqlhNzdZA4JF482F0sgMX0kbIyrGuEIpTm5GDaP1CokwOAaYlBgCyE8xhmSRMu05dJbAg6GDxpdOoLNGaad+/bLpUocZZcabyurQsJSFsFrAhxrVUoZgqvtMQ0vhyCrnTQwqReCoOzEQ0wzTsLpkur1pH6KE3pAfDH+Z8LeI8VOhGsgw9ly4eFqGPrO6UDXHw6m5A/ofaTPF/10uwfX5eZtvnji6OPxd/vX385W4wvzuTxh1tpivO3vx0tPsrb0e3i9PT3xfLNc/n59JSYaRqH99LpOkAbqlmi46ClqGMo/o0jbz76ZLL5QJ/UmN6SrSVia0JVlxM1nr/IXmTPcu9kriuFN9ScxK7/HXZIL22NO8QfsO40xyFT4ZxYDw7cSebj7Oj+8Ie7pBvtGRApiPNsmLN0jS+GQVHCk2RhnRomRUkkjQZJ1ljHkFoJkUaMTZTatmFZUTR/znmo0Iim4iawV81/Id7RIE/7WgTJhL9X8XFTTqwYFin4mVT+isH4K94aFB6HMa2C51wiG6Io2YNknWRMihI+QiQrRWBRpOFzdIV2GEQC3rdC01bqZMEk51YW7RrMTk2ngqutEYGJ2R0hbyelMjOZrWIPjjXrla0YVCfiaV8boYJDxtFexfOcqJQth2mdhmfFk3cYFSVx/xqc0SijTdhZSkwt92B+E/NrwqNBGTQ3J1vZHsRC1JznrYRfY0GXDKhV7MfZa/HfEdK87EFlzqgo4XMlUFJ5zU/CNx3PvLVcJrcKbja7QzEMn+tb0fw40n5EirtN1RZ4D4O2mjlVUdn4QaucXTY+pLVDpSVtX0MV1XfaTeR2y0MqEA/6//Y3zbvqtC1GN6UyvDuHhVWNQTgvdOknfaFM9npot6xLbQxQ8kAZZR6Wzl57dB6udShsE0Df6eGbOr48EdQLbyRSLfymXbYIL3/9+em9Kln4dSWBAjJ7yFH0aTcuLS4ybz7KjslNqkJCfq+p9Rqks95bp1e6miWistW6tI1PTu57vlOld5RYokPvzE9kG6gxXJLpsT5/1fUEyHP4y+mA5K+uNkGhW4uimxE6PASKFHUV4LEWdJ9AoABijBV9TMjXBEQITi8barMVhAJ7SmdVFoehOtBbg5mxqydq/PTVzvRN8+66Q7efeA37H4mBNQeeDQAA

**Comment by zachsa** [comment]
I see. That wasn't working this morning when I tested that.
