### ISSUE TITLE
Version lookups not working for packages not yet built

### ISSUE THREAD

**Issue by guybedford** [jspm/generator#189]
We have build queue requests to the build queue JSPM API built into the generator, but these only apply for packages that are known versions.

The version resolver itself in the generator will throw a version not found lookup error for versions not yet built.

The best way to resolve this is likely to update the version resolver itself to not depend on the build status of a package, but instead to use the npm registry resolver source of truth directly.

Then if a package build is missing we can properly throw an error about this, instead of a version resolution error.

**Comment by Aslemammad** [comment]
I see, how I can resolve this and work on? there are any tests in that regard?
