### ISSUE TITLE
Improved provider support

### ISSUE THREAD

**Issue by guybedford** [jspm/generator#208]
Check and confirm current provider support across major CDNs:

* jsdelivr
* esm.sh (seeing `externals=*`?)
* cdnjs
* unpkg
* skypack
* others?

**Comment by guybedford** [comment]
@Bubblyworld can we close this one?

**Comment by Bubblyworld** [comment]
@guybedford Currently we don't have providers for `cndjs` and `esm.sh`, I'll note it as a TODO after I get to the other stuff you assigned me.

**Comment by guybedford** [comment]
Let's ignore cdnjs then, and just track `esm.sh` support in https://github.com/jspm/generator/issues/269.

**Comment by Bubblyworld** [comment]
Okay cool, yeah, I think that makes sense. For future reference if we ever want to support `cdnjs`, we can do it by serving `package.json` from another source in the provider with the `"exports"` and `"imports"` stripped, and remapping files according to the `"autoupdate"` field above.
