### ISSUE TITLE
CI error - flake or actual bug?

### ISSUE THREAD

**Issue by guybedford** [jspm/generator#217]
Getting - 

```
error: Uncaught ReferenceError: Cannot access 'default' before initialization
    at https://ga.jspm.io/npm:@babel/helper-create-class-features-plugin@7.21.0/lib/index.js:1:1056
node:internal/errors:857
  const err = new Error(message);
              ^

Error: Command failed: deno run --reload --unstable --no-check --allow-all --import-map=/tmp/map.json /tmp/app.js
    at __node_internal_genericNodeError (node:internal/errors:857:15)
    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at denoExec (file:///home/runner/work/generator/generator/test/deno.js:18:3)
    at file:///home/runner/work/generator/generator/test/deno/self.test.js:24:7 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 3021,
  stdout: null,
  stderr: null
}
```

**Comment by Bubblyworld** [comment]
It seems like a bug in `@babel/helper-create-class-features-plugin@7.21.0`, which was published yesterday. I think it's pulled in as a transitive dependency in the test - not sure what we can do about it until it gets patched, other than change/disable the test.

**Comment by Bubblyworld** [comment]
Scrap that, as discussed yesterday it seems to be a CDN build error. Currently no matter what version I pin it to with `resolutions` there's still a failure.

**Comment by Bubblyworld** [comment]
On the other hand, if you look at the online generator's source it's currently linked to `7.19.0` and seems to be working:

<img width="1325" alt="Screenshot 2023-02-23 at 13 38 20" src="https://user-images.githubusercontent.com/6214591/220895483-3af0ea24-a6eb-4000-84a6-41e37a71dcd2.png">
