### ISSUE TITLE
feat: option for nodemodules to create absolute urls

### ISSUE THREAD

**Issue by daKmoR** [jspm/generator#25]
I am using

```js
import { Generator } from '@jspm/generator';

const generator = new Generator({
  defaultProvider: 'nodemodules',
});

// Install a new package into the import map
await generator.install('lit');

console.log(JSON.stringify(generator.getMap(), null, 2));
```

to generate an import map that I am using on multiple files
```
index.html
page-a/index.html
page-b/index.html
...
```

## Expected output

```json
{
  "imports": {
    "lit": "/node_modules/lit/index.js"
  },
  "scopes": {
    "/node_modules/": {
      "@lit/reactive-element": "/node_modules/@lit/reactive-element/development/reactive-element.js",
      "lit-element/lit-element.js": "/node_modules/lit-element/development/lit-element.js",
      "lit-html": "/node_modules/lit-html/development/lit-html.js"
    }
  }
}
```

## Actual output

```json
{
  "imports": {
    "lit": "./node_modules/lit/index.js"
  },
  "scopes": {
    "./node_modules/": {
      "@lit/reactive-element": "./node_modules/@lit/reactive-element/development/reactive-element.js",
      "lit-element/lit-element.js": "./node_modules/lit-element/development/lit-element.js",
      "lit-html": "./node_modules/lit-html/development/lit-html.js"
    }
  }
}
```

relative URLs will only work on the root index.html as soon as we are in a subfolder it fails.
For example in `page-a/index.html` it will then search for `page-a/node_modules/lit/index.js` which does not exist.

## Suggestion

I assume we would need some sort of flag for that? 🤔
or should it be absolute by default and add a flag to be relative? 🤔

How about

```js
const generator = new Generator({
  absoluteNodeModulesUrls: true, // potentially defaults to true and to get relative you put false here
  defaultProvider: 'nodemodules',
});
```
---

PS: I also tried with
```js
const generator = new Generator({
  mapUrl: '/',
  defaultProvider: 'nodemodules',
});
```

but that gave an error `Invalid URL: /`

**Comment by guybedford** [comment]
The assumption of the `mapUrl` option is that it is the URL of the import map in the browser - so all relative URLs are relative to the import map. Eg if you set the `mapUrl` to `about:blank` or something all URLs should be absolute then. But it will then include the full `file:` URL scheme.

Agreed a `publicUrl` or `rootUrl` option would be useful for handling the server mapping, will definitely add that.
