### ISSUE TITLE
generate .d.ts instead of .ts

### ISSUE THREAD

**Issue by tjx666** [jspm/generator#252]
reproduce: 

1. git clone https://github.com/tjx666/wpm-issue
2. pnpm install
3. tsc

![image](https://user-images.githubusercontent.com/41773861/223363011-b03a56e1-321c-4bb9-8ba7-4e7badab12c9.png)

**Comment by Bubblyworld** [comment]
Related to #234, these are actual typing issues in the generator (we don't have strict typing enabled, should get on that!).

**Comment by RyanCavanaugh** [comment]
FYI: this is a critical misconfiguration. The `types` field *cannot* point to a `.ts` file; this is going to effectively break any TypeScript consumer of the package.

**Comment by Bubblyworld** [comment]
Ah, ok, thanks! I see what the issue is now - posted a fix.
