### ISSUE TITLE
Improved deno provider support

### ISSUE THREAD

**Issue by Bubblyworld** [jspm/generator#272]
Currently the deno provider throws when it resolves an `npm:` package specifier. This makes some sense, since denoland doesn't host npm packages, but it's a bit annoying because whenever an installed package has an npm package as a transitive dependency it's basically unusable with `jspm` (see https://deno.land/manual@v1.31.2/node/npm_specifiers).

Not sure what to do here - perhaps we should direct the user to the `providers` option docs and advise them to configure a non-deno provider to resolve `npm:`-registry stuff? At the moment the error is very obscure unless you understand generator internals.

**Comment by guybedford** [comment]
Agreed we should definitely not throw on this - we can treat it the same as we do for `node:` URLs (in Node.js of course).
