### ISSUE TITLE
Hook into `deno.json` when resolving dependencies for denoland packages.

### ISSUE THREAD

**Issue by Bubblyworld** [jspm/generator#289]
```
$ jspm i denoland:fresh/runtime.ts

Error: Deno provider does not support the npm registry for package "preact" - perhaps you mean to install "denoland:preact"?
```

`fresh` uses an import map for bare specifiers like `preact`, but the generator currently ignores the `deno.json`, so when it tries to resolve `preact` we hit the global fallback, which is to use `npm:preact`, and the deno provider throws as it doesn't support the npm registry.

**Comment by guybedford** [comment]
The workflow currently being recommended here is `jspm i denoland:fresh/runtime.ts -m deno.json` or `jspm i denoland:fresh/runtime.ts -o browser.html --env=browser` for dual browser / Deno workflows.

**Comment by guybedford** [comment]
Ah I realise you meant this for secondaries. This is not something we want to do actually because the `deno.json` is an exact resolution map not a constraint, whereas package management always operates on constraints (ie package.json dependencies).
