### ISSUE TITLE
TypeError: s is not a function on newer versions of an importmapped package

### ISSUE THREAD

**Issue by wbugenis** [jspm/generator#318]
I'm not entirely sure if this is your department, but figured I'd give it a try in case you can offer me any advice, or at least point me in the right direction.
I'm using the `agora-rtc-sdk-ng` package in my rails app (using importmap-rails), which works flawlessly with version 4.15.1, with this link - https://ga.jspm.io/npm:agora-rtc-sdk-ng@4.15.1/AgoraRTC_N-production.js

However, when I try  pin any of the more recent versions, up to the latest of 4.18.2, linked here -
https://ga.jspm.io/npm:agora-rtc-sdk-ng@4.18.2/AgoraRTC_N-production.js, I get the following error -
![image](https://github.com/jspm/generator/assets/6378179/4c5564f8-572b-4e58-a098-3f6c482f2027)

Is there anything I can do as an end user of this package to resolve this issue, or is this something the developer of the package would have to fix? I'm not sure if this an answerable question, but what would the fix be, if the developer has to do it?

Thanks for your help, and sorry if this is outside of your wheelhouse - I've reached out to their support team as well but they haven't figured out a resolution for it yet, so I figured I'd give you guys a shot.

**Comment by guybedford** [comment]
Thanks for posting the bug! I was able to track this down to a jspm.io CDN build error and upload a fix - it should be working now if you clear your browser cache.
