### ISSUE TITLE
Support for passing an existing import map as the base for the generator.

### ISSUE THREAD

**Issue by vovacodes** [jspm/generator#33]
The use-case is when you already have an import map but you want to add extra dependencies to it.

**Comment by guybedford** [comment]
The `inputMap` option is exactly the thing to use here, basically just passing that argument from the main generator.

A PR would be great if you're up for it, and let me know if I can assist further.

**Comment by guybedford** [comment]
(And also if you hit scenarios where the interactions on the existing API don't work out as you'd expect them to)

**Comment by vovacodes** [comment]
yeah I'm gonna open one, I'll reach out if I'm blocked

**Comment by guybedford** [comment]
Landed in https://github.com/jspm/generator/pull/34.
