### ISSUE TITLE
Error: Module not found: https://cdn.jsdelivr.net/npm/dayjs@1.11.11/locale/en

### ISSUE THREAD

**Issue by colinmollenhour** [jspm/generator#355]
This error was generated on generator.jspm.io by adding the dependency "@cubejs-client/core". It works when jspm.io is the CDN but not for jsdelivr. However, jsdelivr does host the file using the .js extension here: https://cdn.jsdelivr.net/npm/dayjs@1.11.11/locale/en.js

```
Error: Module not found: https://cdn.jsdelivr.net/npm/dayjs@1.11.11/locale/en imported from https://cdn.jsdelivr.net/npm/@cubejs-client/core@0.35.23/dist/cubejs-client-core.esm.js
```

**Comment by guybedford** [comment]
I've transferred this issue to the generator repo as an enhancement for supporting extension searching for exports paths that fail their original request.

CommonJS supports this pattern in Node.js, so it seems a sensible pattern to support in the name of compatibility.

**Comment by guybedford** [comment]
Fixed in https://github.com/jspm/generator/pull/359, will aim to post a generator release this week.

**Comment by colinmollenhour** [comment]
Thanks @guybedford !
