### ISSUE TITLE
Improve compatibility for running in browsers

### ISSUE THREAD

**Issue by salmenf** [jspm/generator#375]
Hello! First of all, great project, love the idea of using importmaps for dependency management.

That said, I was struggling to use this package on the client side: It kept failing with `createHash` is not a function. After replacing the `crypto` dependency with `@jspm/core/nodelibs/crypto` similar to how you solve it [for your sandbox](https://github.com/jspm/generator.jspm.io/blob/main/src/api.js), it works.

Maybe the dependency on `crypto` could be dropped in favor of `crypto.subtle`? The `crypto.subtle.digest` seems to do the same. There's an [example on MDN](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest#converting_a_digest_to_a_hex_string) that seems to do broadly the same as your `getIntegrity` function.

**Comment by guybedford** [comment]
Thanks for the suggestion, added in https://github.com/jspm/generator/pull/376.
