### ISSUE TITLE
`defaultProvider` doesn't affect package resolution

### ISSUE THREAD

**Issue by salmenf** [jspm/generator#379]
Consider this snippet:
```ts
const generator = new Generator({defaultProvider: "jsdelivr"})
generator.install("mypkg/mymodule.js")
```
Just from configuring, I'd expect this to fully run using `jsdelivr`. But actually, the `package.json` used for resolution is still fetched from `jspm.io`. As `jsdelivr` seems to update instantly (or at least quickly on demand), and `jspm.io` takes a little more time, this causes a kind of of "out-of-sync" issue and resolution fails (`unable to resolve...`).

I suggest that this setting should also affect how the `package.json` is fetched. A separate setting would also be possible.

Other info:
- I'm running `@jspm/generator@2.2.0` in a browser environment (thanks for that last fix, btw! :) )

**Comment by guybedford** [comment]
Yes, the problem here is updating the resolver to use a generic npm resolver in https://github.com/jspm/generator/blob/main/src/providers/jsdelivr.ts#L20 instead of sharing the JSPM resolver.
