### ISSUE TITLE
Any plans for CLI support?

### ISSUE THREAD

**Issue by Hawmex** [jspm/generator#64]
I just used the online generator and it was really good. But I think using an import map generator in the CLI which automatically generates import map from `package.json` would be very handy. I'm wondering if there are any plans to support this approach, too.

**Comment by rajasegar** [comment]
Yes, a CLI will come handy and also we can also add npm scripts based on it to install, re-install or update the import maps.
Some time back I created this CLI to generate project scaffolds based on import maps with various cdns
https://github.com/rajasegar/unpack
May be I can give a shot for the CLI if we are clear with the MVP requirements

**Comment by Bubblyworld** [comment]
This is being developed at [`jspm/jspm`](/jspm/jspm), closing for now.
