### ISSUE TITLE
Modify import map after loading @jspm/generator

### ISSUE THREAD

**Issue by FallingSnow** [jspm/generator#73]
I'm successfully using @jspm/generator to generate my import map. Then adding that map to the document head and executing modules. This however only works with `es-module-shims` and the `module-shim`/`importmap-shim` script types. If I don't use the shim I get `An import map is added after module script load was triggered.`

Is there a way to use @jspm/generator in the browser without initializing a module so I can avoid the `An import map is added after module script load was triggered.` error?

**Comment by danielkov** [comment]
> @FallingSnow in this case you should use an iframe to handle it!

Sorry for commenting on this already closed issue, but it's the only information I've found about dynamic import maps. If it's not too much to ask, would you mind giving me some pointers, how one would implement dynamic import maps with an iframe? Thanks!

**Comment by FallingSnow** [comment]
If I remember correctly (I might be wrong) but the `An import map is added after module script load was triggered.` is a limitation of the browser. Therefore the proposed work around is by guybedford is to use an iframe to workaround the issue, how to do that I'm not really sure. Perhaps you can load your generating modules, generate the dynamic import map, then load your site in an iframe. Although this seems kind of hacky and I'm not sure if there would be any context restrictions.

I do remember that the method I was trying to do proved to be too unstable and I reverted to just prebuilding the import map.

**Comment by danielkov** [comment]
That iframe solution is not much better than just saving the importmap in `localStorage` and refreshing the page with a script that re-creates the import map from `localStorage` after the refresh. I thought there was a way to break out of the `iframe` and affect the parent scope. Thanks for the explanation!

**Comment by FallingSnow** [comment]
I believe iframes have lower restrictions if they share the same domains, so that may be possible. But again to me it seems like a, all be it fun, but over complicated solution.
