### ISSUE TITLE
devDependencies scoping

### ISSUE THREAD

**Issue by guybedford** [jspm/generator#84]
Currently devDependencies is always used as a fallback if a dependency has no other range declaration.

But it turns out this is sometimes incorrect eg in the case of react-query, it has an optional dependency on react-dom but doesn't specify a version range. yet the version in devDependencies to React 16 is overly restrictive (https://ga.jspm.io/npm:react-query@3.32.1/package.json).

The generator should always ignore "devDependencies" for packages deemed non-local. The hard part is then just scoping which packages are deemed local versus non-local. For such a definition "devDependencies" restriction can then be performed, using an implicit `"*"` assumption instead as we do for no "devDependencies" match.

**Comment by guybedford** [comment]
One definition of local that might work:

The local package of any generation operation is the package boundary of the package.json file contained within the mapUrl provided. For a given module, one can find its package scope boundary via the package.json lookup, and if it matches this package boundary we can say it is _the local package_, and then resolve devDependencies for it.

@giltayar does that align with your intuition as a judgement of when to apply `devDependencies` versus unscoped ranges?

**Comment by giltayar** [comment]
Yes!

**Comment by guybedford** [comment]
Landed in https://github.com/jspm/generator/pull/88.
