### ISSUE TITLE
conditional lazy imported packages are preloaded

### ISSUE THREAD

**Issue by jimmywarting** [jspm/generator#90]
https://jspm.dev/stream-consumers loads "node:buffer" and "/npm:fetch-blob@3" even doe they are not necessary...

**Comment by guybedford** [comment]
Thanks, I've pushed up a patch fix to the CDN builder. Packages previously published will need to wait for the next major to get this update, or you can let me know if there are other packages you are affected by and I can run a manual cache flush.
