### ISSUE TITLE
Add a simple binary?

### ISSUE THREAD

**Issue by rauschma** [jspm/generator#98]
I’m not sure if that is possible, but I’d find it useful if I could generate an import map like this:

```
npx @jspm/generator node_modules/
```

**Comment by fusionstrings** [comment]
Did you mean, one importmap for every package in node_modules?

hypothetically considering following an entry point for the generated importmap for each package?

```js
import package from 'package'
```

**Comment by guybedford** [comment]
Duplicate of https://github.com/jspm/generator/issues/64. There will eventually be a CLI relaunch when the timing is right.
