### ISSUE TITLE
Generator CDN API throwing 401 Unauthorized error for jspm.system provider

### ISSUE THREAD

**Issue by learnwithsumit** [jspm/generator#99]
I am trying to generate import map using the CDN API using "jspm.system" provider. Few days ago it was working, but now it is throwing 401 Unauthorized error! Please check the screenshot attached.
** Please note that it is working for other providers like "unpkg"!

<img width="1023" alt="Screenshot 2022-01-31 at 3 28 15 AM" src="https://user-images.githubusercontent.com/73503432/151718724-7b4cb55f-b55c-495b-9e0b-13d624c793be.png">

**Comment by guybedford** [comment]
Thanks for posting, this was due to an overloaded subservice combined with Google for some reason caching error responses in the cloud run pool, affecting some requests. I've expanded the service capacity and am looking into why the health check failed. This should be working now though.
